### ISSUE TITLE
Application crashing on onlong press

### ISSUE THREAD

**Issue by akshay2211** [Danylo2006/HashTagHelper#17]
hello @danylovolokh,
whenever I  long press on any hashtag, my application is getting crashed, with the error
`Attempt to invoke virtual method 'int android.widget.Editor$SelectionModifierCursorController.getMinTouchOffset()' on a null object reference`

**Comment by tamirherman** [comment]
Add:

                    mTextView.setOnLongClickListener(new View.OnLongClickListener(){
                        @Override
                        public boolean onLongClick(View v){
                            //just consume the event
                            return true;
                        }
                    });
