### ISSUE TITLE
Gradle dependency to include it in Android Studio

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Danylo2006/HashTagHelper#2]
Thanks for creating this. What is the gradle dependency for it? Or should i include as module?

**Comment by danylovolokh** [comment]
Please include as module.
I plan to add a dependency within a week

**Comment by danylovolokh** [comment]
Added gradle dependency
dependencies {
    compile 'com.github.danylo2006:hashtag-helper:1.0.0'
}

**Comment by Shajeel-Afzal** [comment]
Thank you so much for that.
