### ISSUE TITLE
#first_second is not working

### ISSUE THREAD

**Issue by hishambakr** [Danylo2006/HashTagHelper#3]
Hello Danylo,
                   Thank you for great effort. I face an issue that if I wrote hashtag of 2 words like this" #first_second, first word only is highlighted . please advise.

Thank you,
Hisham

**Comment by danylovolokh** [comment]
Hi, 

Yes, there is no option to chose which symbols can be in hashtag. Currently it's only digits or/and letters.

This method is responsible for finding your underscore "_" and finishing highlighting if it finds it.
private int findNextNotLetterDigitChar(CharSequence text, int start)

You can change it and have functionality you want

**Comment by ghost** [comment]
@hisham2007 check this commit
https://github.com/sabeersas/HashTagHelper/commit/9bfa076db7ea5a0ac44f137b744d91662d086c20

change 
boolean isLetterOrDigit = Character.isLetterOrDigit(sign);
to
boolean isLetterOrDigit = (Character.isLetterOrDigit(sign) || sign=='_');

**Comment by hishambakr** [comment]
thanks for reply. i suggest to change implementationto end hashtag in case
of space or \n

**Comment by danylovolokh** [comment]
Pushed fix. 
I will update repository and Readme.md soon

Thanks for your feedback guys.

**Comment by danylovolokh** [comment]
Repository updated. Please use compile 'com.github.danylo2006:hashtag-helper:1.1.0'
and specify '_' as additional symbol when creating HashTagHelper:

mTextHashTagHelper = HashTagHelper.Creator.create(getResources().getColor(R.color.colorPrimary), null, '_');
