### ISSUE TITLE
Failed to resolve: com.github.danylo2006:hashtag-helper:1.1.0

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Danylo2006/HashTagHelper#7]
Hi

I am trying to update the version of the library and i am getting the error: `Failed to resolve: com.github.danylo2006:hashtag-helper:1.1.0`, can you please recheck and correct?

Thanks.

**Comment by danylovolokh** [comment]
Yes, the packages was re-linked to:

compile 'com.github.danylovolokh:hashtag-helper:1.1.0'. 

Sorry for inconvenience

**Comment by Shajeel-Afzal** [comment]
Thank you.
