### ISSUE TITLE
How to have the same functionality with @ mentions

### ISSUE THREAD

**Issue by mik-dass** [Danylo2006/HashTagHelper#9]
I am thinking about using this library in my app. But I also require the library to work with @ mentions . Please tell me where to make changes to achieve functionalities with the @ mentions. Please reply.

**Comment by danylovolokh** [comment]
Find method called setColorsToAllHashTags()
And change this line of code:
if(sign == '#'){

**Comment by mik-dass** [comment]
@danylovolokh Thank you.I figured it out myself after going through the code once again.Your library saved me big time .Thank you for this awesome library...:)
